--- @class currentzone
--- @field public Dungeon boolean Are we in a dungeon
--- @field public Gravity MQFloat Gravity
--- @field public ID number Zone ID
--- @field public Indoor boolean Are we indoors?
--- @field public MaxClip MQFloat Maximum clip plane allowed in zone
--- @field public MinClip MQFloat Minimum clip plane allowed in zone
--- @field public Name string Full zone name
--- @field public NoBind boolean Can we bind here?
--- @field public Outdoor boolean Are we outdoors?
--- @field public ShortName string Short zone name
--- @field public SkyType number Sky type
--- @field public Type number Zone type:0=Indoor Dungeon 1=Outdoor 2=Outdoor City 3=Dungeon City 4=Indoor City 5=Outdoor Dungeon
--- @field public FOgOnOff number off
--- @field public ZoneFlags number # Zone flags
--- @field public SafeY MQFloat # Safe Y coordinate
--- @field public SafeX MQFloat # Safe X coordinate
--- @field public SafeZ MQFloat # Safe Z coordinate
--- @field public SafeN MQFloat # Safe Y coordinate
--- @field public SafeW MQFloat # Safe X coordinate
--- @field public SafeU MQFloat # Safe Z coordinate
--- @field public ToString string Same as Name