--- @class zone
--- @field public ID MQInt # ID of the zone
--- @field public Name MQString # Full zone name
--- @field public ShortName MQString # Short zone name
--- @field public ZoneFlags MQInt # Zone flags
--- @field public SafeY MQFloat # Safe Y coordinate
--- @field public SafeX MQFloat # Safe X coordinate
--- @field public SafeZ MQFloat # Safe Z coordinate
--- @field public SafeN MQFloat # Safe Y coordinate
--- @field public SafeW MQFloat # Safe X coordinate
--- @field public SafeU MQFloat # Safe Z coordinate
--- @field public ToString MQString # Same as Name
